#-------------------------------
# Site Settings
title: Hannes Hapke
logo: # You can add own logo. For example '/images/logo.png'.
description: ML Engineering Leader & Author. Specialist in production machine learning systems, MLOps, and generative AI applications.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.hanneshapke.com" # the base hostname & protocol for your site, e.g. http://example.com
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Author Settings
author:
  author__name: Hannes Hapke
  author__bio: ML Engineering Leader and bestselling author with expertise in production machine learning systems, MLOps, and generative AI. Co-author of four O'Reilly and Manning publications on machine learning engineering.
  author__avatar: '/images/01-1.jpg'

social:
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/hanneshapke/"}


#-------------------------------
# Hero Settings
hero:
  hero__title: Building Production ML Systems That Scale
  hero__description: ML Engineering Leader, author of four machine learning books, and Google Developer Expert. I help organizations architect robust ML systems from research to production, specializing in MLOps, generative AI deployment, and scalable data platforms.
  hero__image: '/images/01.jpg'


#-------------------------------
# Newsletter
mailchimp: enable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp__identifier: gmail.us21.list-manage.com/subscribe/post?u=8e187272c15ddc24057841e70&amp;id=dff698e86b&amp;f_id=0053c0e1f0 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
mailchimp__input__text: Your email address
mailchimp__button__text: Get ML Insights


# #-------------------------------
# # Gallery Footer Section
# gallery:
#   gallery__title: Gallery
#   gallery__columns: 3
#   gallery__images:
#     - alt: 'Rest'
#       url: '/images/100.jpg'
#     - alt: 'Lifestyle'
#       url: '/images/101.jpg'
#     - alt: 'Hobby'
#       url: '/images/102.jpg'
#     - alt: 'Notes'
#       url: '/images/103.jpg'
#     - alt: 'Rest'
#       url: '/images/104.jpg'
#     - alt: 'Hobby'
#       url: '/images/105.jpg'
#     - alt: 'Fashion'
#       url: '/images/106.jpg'
#     - alt: 'Notes'
#       url: '/images/107.jpg'
#     - alt: 'Rest'
#       url: '/images/108.jpg'


#-------------------------------
# # Contact Settings
# contact:
#   email: your@email.com # Add your email for contant form
#   description: Reach out if you have questions regarding Machine Learning and MLOps. # Add a description of your form

# NOTE
# Menso theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: demo-menca # Add your shortname for Disqus Comment. For example demo-menca


#-------------------------------
# Google Analytics
# google-analytics: # Add your GA Tracking Id


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext


include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed
